USE db1;

CREATE TABLE IF NOT EXISTS `profile` (
		`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
		`account` VARCHAR(40) NOT NULL,
		`passwd` VARCHAR(40) NOT NULL,
		`ban` TINYINT(1) NOT NULL DEFAULT '0',
		`lasttime` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
		`lastip` VARCHAR(16) NOT NULL DEFAULT '',
		PRIMARY KEY (`id`),
		UNIQUE KEY `a` (`account`)
		) ENGINE = innoDB DEFAULT CHARSET = utf8;
