USE db1;

CREATE TABLE IF NOT EXISTS `profile` (
	`id` BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`account` VARCHAR(256) UNIQUE NOT NULL,
	`passwd` VARCHAR(256) DEFAULT NULL
) ENGINE = innoDB DEFAULT CHARSET = utf8;
