USE db2;

CREATE TABLE IF NOT EXISTS `user` (
	`id` BIGINT UNSIGNED NOT NULL,
	`nickname` VARCHAR(40) NOT NULL,
	`gender` TINYINT(4) DEFAULT NULL,
	`age` INTEGER DEFAULT NULL,
	`signature` VARCHAR(255) DEFAULT NULL,
	`email` VARCHAR(255) DEFAULT NULL,
	`city` VARCHAR(40) DEFAULT NULL,
	`introduction` VARCHAR(255) DEFAULT NULL,
	`status` TINYINT(3) NOT NULL DEFAULT '0',
	`score` INTEGER NOT NULL DEFAULT '0',
	`money` INTEGER NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`),
	UNIQUE KEY `a` (`nickname`)
) ENGINE = innoDB DEFAULT CHARSET = utf8;
